# Generated by Django 3.1.2 on 2021-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
