# Generated by Django 3.1.2 on 2021-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210501_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='incomeModel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
